# **EXP3: Compute DCT and IDCT to perform signal compression**

In [1]:
import numpy as np

In [4]:
x = np.array(list(map(int,input().split())))  
N = len(x)

1 3 5 7


## Calculate DCT

In [5]:
mat = np.zeros((N, N))

for i in range(N):
  for j in range(N):
      if i == 0:
        mat[i][j] = np.sqrt(1/N)
      else:
        mat[i][j] = np.sqrt(2/N)*np.cos((np.pi*((j*2)+1)*i)/(2*N))
print(mat)

[[ 0.5         0.5         0.5         0.5       ]
 [ 0.65328148  0.27059805 -0.27059805 -0.65328148]
 [ 0.5        -0.5        -0.5         0.5       ]
 [ 0.27059805 -0.65328148  0.65328148 -0.27059805]]


In [6]:
F = np.dot(mat,x)
F

array([ 8.00000000e+00, -4.46088499e+00, -1.33226763e-15, -3.17025336e-01])

## Calculate IDCT

In [7]:
IDCT = []
for i in range(N):
  sum = 0
  for j in range(N):
    if i == 0:
      sum += np.sqrt(1/N)
    else:
      sum += (np.sqrt(2/N)*F[j]*np.cos((np.pi*((i*2)+1)*j)/(2*N)))
  IDCT.append(sum)

IDCT

[2.0, 4.656854249492382, 6.65685424949238, 8.656854249492381]